# -*- coding: utf-8 -*-

WITHINGS_GENDER_MALE = 0
WITHINGS_GENDER_FEMALE = 1

WITHINGS_CATEGORY_MEASURE = 1
WITHINGS_CATEGORY_TARGET = 2

WITHINGS_ATTRIBUTION_USER = 0
WITHINGS_ATTRIBUTION_AMBIGUOUS = 1
WITHINGS_ATTRIBUTION_MANUAL = 2
WITHINGS_ATTRIBUTION_INITIAL = 3
